name: simonews
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.4
  http: ^0.12.0+4
  shared_preferences: ^0.5.6+3

  cupertino_icons: ^0.1.3

  webview_flutter: ^0.3.20
  url_launcher: ^5.1.4
  url_launcher_web: ^0.1.0
  share: ^0.6.3+6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

